### ISSUE TITLE
Can not runnable with error

### ISSUE THREAD

**Issue by bluerxing** [pietrobarbiero/pytorch_explain#2]
the py script I run:

```
import torch
import torch_explain as te
from torch.nn.functional import one_hot

x0 = torch.zeros((4, 100))
x_train = torch.tensor([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1],
], dtype=torch.float)
x_train = torch.cat([x_train, x0], dim=1)
y_train = torch.tensor([0, 1, 1, 0], dtype=torch.long)
y_train_1h = one_hot(y_train).to(torch.float)

layers = [
    te.nn.EntropyLinear(x_train.shape[1], 10, n_classes=y_train_1h.shape[1]),
    torch.nn.LeakyReLU(),
    torch.nn.Linear(10, 4),
    torch.nn.LeakyReLU(),
    torch.nn.Linear(4, 1),
]
model = torch.nn.Sequential(*layers)

optimizer = torch.optim.AdamW(model.parameters(), lr=0.001)
loss_form = torch.nn.BCEWithLogitsLoss()
model.train()
for epoch in range(2001):
    optimizer.zero_grad()
    y_pred = model(x_train).squeeze(-1)
    loss = loss_form(y_pred, y_train_1h) + 0.0001 * te.nn.functional.entropy_logic_loss(model)
    loss.backward()
    optimizer.step()

from torch_explain.logic.nn import entropy
from torch.nn.functional import one_hot

y1h = one_hot(y_train)
explanation, _ = entropy.explain_class(model, x_train, y1h, x_train, y1h, target_class=1)

from torch_explain.logic.metrics import test_explanation, complexity

accuracy, preds = test_explanation(explanation, x_train, y1h, target_class=1)
explanation_complexity = complexity(explanation)
```

Error:

```
Traceback (most recent call last):
  File "/home/cil/DataFolder/PycharmProjects/logic/logic_test.py", line 39, in <module>
    explanation, _ = entropy.explain_class(model, x_train, y1h, x_train, y1h, target_class=1)
  File "/home/cil/miniconda3/lib/python3.9/site-packages/torch_explain/logic/nn/entropy.py", line 111, in explain_class
    c_correct, y_correct, correct_mask, active_mask = _get_correct_data(c, y, train_mask, model, target_class,
  File "/home/cil/miniconda3/lib/python3.9/site-packages/torch_explain/logic/nn/entropy.py", line 436, in _get_correct_data
    active_mask = y[train_mask, target_class] == 1
IndexError: tensors used as indices must be long, byte or bool tensors
```

Environment:
```
Python                  3.9.7
pytorch                   1.10.2          py3.9_cuda10.2_cudnn7.6.5_0
torch-explain             1.3.0
```

**Comment by pietrobarbiero** [comment]
Hi @bluerxing! Thanks for bringing this up and sorry for the delay in responding to this issue. I have just updated the readme and the interface to explanation methods in the last commit. The changes should have now fixed the issue. Anyway, let me know :)
